import { useEffect, useState } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { ErrorState, Icon } from '../components/States';
import { api } from '../api/client';

const roles=[['patient','Patient','Start or continue your visit','user'],['doctor','Doctor','Open the clinical workspace','doctor'],['admin','Hospital Admin','Manage hospital doctors','home']];
export default function Login(){const auth=useAuth(),nav=useNavigate(),loc=useLocation();const selected=new URLSearchParams(loc.search).get('role');const [accounts,setAccounts]=useState([]),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(null);
 useEffect(()=>{api.demoAccounts().then(r=>setAccounts(r.accounts||[])).catch(()=>setAccounts([]))},[]);
 if(!selected||!roles.some(r=>r[0]===selected))return <div className="auth-shell"><div className="auth-form-wrap"><div className="auth-form-card role-login-choice"><div className="eyebrow">AAROGYASAAR</div><h1>Choose how you want to continue</h1><div className="role-cards">{roles.map(([id,label,sub,icon])=><button key={id} className="role-card" onClick={()=>nav(`/login?role=${id}`)}><span className="role-icon"><Icon name={icon}/></span><span><strong>{label}</strong><small>{sub}</small></span><b>→</b></button>)}</div><button className="back-role" onClick={()=>nav('/')}>← Back</button></div></div></div>;
 const account=accounts.find(a=>a.role===selected);function useDemo(){if(!account)return;setEmail(account.email);setPassword(account.password);setError(null)}
 async function submit(e){e.preventDefault();setBusy(true);setError(null);try{const r=await auth.login(email.trim(),password);if(r.user.role!==selected){await auth.logout();throw new Error('This account cannot open this workspace.')}nav(selected==='patient'?'/patient/visit':selected==='doctor'?'/doctor':'/admin',{replace:true})}catch(e2){setError(e2)}finally{setBusy(false)}}
 const label=roles.find(r=>r[0]===selected)?.[1];return <div className="auth-shell"><div className="auth-visual"><button className="wordmark" onClick={()=>nav('/')}><span className="logo-heart">♥</span><span>Aarogya<span>Saar</span></span></button><div className="auth-visual-copy"><div className="eyebrow">{selected==='patient'?'PATIENT CARE':selected==='doctor'?'CLINICAL CARE':'HOSPITAL OPERATIONS'}</div><h1>{selected==='patient'?'Your story starts here.':selected==='doctor'?'A clearer view of every patient story.':'A calmer way to manage the hospital.'}</h1><p>Secure access to the right AarogyaSaar workspace.</p></div></div><div className="auth-form-wrap"><div className="auth-form-card"><div className="auth-form-head"><span className="mini-icon"><Icon name={selected==='doctor'?'doctor':selected==='admin'?'home':'user'}/></span><div><div className="eyebrow">{label?.toUpperCase()} SIGN IN</div><h2>Welcome back</h2></div></div><ErrorState error={error}/><form onSubmit={submit}><label className="field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button className="btn btn-primary btn-xl full" disabled={busy}>{busy?'Signing you in…':'Continue'} →</button></form>{selected==='patient'&&<p className="auth-switch">New here? <Link to="/register">Create a patient account</Link></p>}{account&&<section className="demo-login"><strong>Quick access</strong><p>Use the preconfigured account for this workspace.</p><button type="button" className="btn btn-outline btn-xl full" onClick={useDemo}>Continue with {label}</button></section>}<button className="back-role" onClick={()=>nav('/login')}>← Choose another role</button></div></div></div>}
