import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import { useAuth } from '../../context/AuthContext';
import { ErrorState, Loading, Section } from '../../components/States';
import AdminLayout from '../../layouts/AdminLayout';
import { SPECIALIZATIONS } from '../../utils/constants';
const empty={name:'',email:'',password:'',specialty:'General Medicine',department:'General Medicine',registration_number:'',room_number:''};
export default function AdminDashboard(){const auth=useAuth();const [hospital,setHospital]=useState(null),[doctors,setDoctors]=useState([]),[patients,setPatients]=useState([]),[departments,setDepartments]=useState([]),[selectedDoctor,setSelectedDoctor]=useState(null),[selectedPatient,setSelectedPatient]=useState(null),[form,setForm]=useState(empty),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(null),[message,setMessage]=useState('');
 async function load(){setError(null);try{const [h,d,p,dep]=await Promise.all([api.adminHospital(auth.token),api.adminDoctors(auth.token),api.adminPatients(auth.token),api.adminDepartments(auth.token)]);setHospital(h.hospital);setDoctors(d.doctors||[]);setPatients(p.patients||[]);setDepartments(dep.departments||[])}catch(e){setError(e)}} useEffect(()=>{load()},[]);
 async function add(e){e.preventDefault();setBusy(true);setError(null);try{const r=await api.adminCreateDoctor(auth.token,{...form,name:form.name.trim(),email:form.email.trim(),password:form.password,registration_number:form.registration_number.trim(),room_number:form.room_number.trim()||'Not assigned',active:true});setMessage(`${r.doctor.name} was registered.`);setForm(empty);setShow(false);await load()}catch(e){setError(e)}finally{setBusy(false)}}
 async function deactivate(d){if(!window.confirm(`Remove ${d.name} from active doctor assignments?`))return;setBusy(true);setError(null);try{await api.adminUpdateDoctor(auth.token,d.id,{name:d.name,email:d.email,password:'',specialty:d.specialty,department:d.department,registration_number:d.registration_number||'',room_number:d.room_number||'Not assigned',active:false});setMessage(`${d.name} is no longer active.`);await load()}catch(e){setError(e)}finally{setBusy(false)}}
 if(!hospital&&!error)return <AdminLayout><Loading label="Loading hospital dashboard…"/></AdminLayout>;
 return <AdminLayout><div className="admin-page-head"><div><div className="eyebrow">HOSPITAL ADMINISTRATION</div><h1>{hospital?.hospital_name||'Hospital Dashboard'}</h1><p>Manage the clinical team and patient flow for today.</p></div><button className="btn btn-primary btn-xl" onClick={()=>setShow(!show)}>{show?'Close':'＋ Register doctor'}</button></div><ErrorState error={error} onRetry={load}/>{message&&<div className="success-message" role="status">✓ {message}</div>}
 <div className="admin-metrics"><div className="admin-metric"><span>Total doctors</span><strong>{doctors.length}</strong></div><div className="admin-metric"><span>Active doctors</span><strong>{doctors.filter(d=>d.active).length}</strong></div><div className="admin-metric"><span>Administrator</span><strong>{auth.user?.name}</strong></div></div>
 {show&&<Section title="Register a doctor"><form className="admin-doctor-form" onSubmit={add}><label className="field"><span>Doctor name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Email</span><input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="field"><span>Account password</span><input required minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="field"><span>Specialization</span><select value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})}>{SPECIALIZATIONS.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Department</span><select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{departments.filter(d=>d.active).map(d=><option key={d.id} value={d.name}>{d.name}</option>)}</select></label><label className="field"><span>Registration number</span><input value={form.registration_number} onChange={e=>setForm({...form,registration_number:e.target.value})}/></label><label className="field"><span>Room number</span><input required value={form.room_number} onChange={e=>setForm({...form,room_number:e.target.value})} placeholder="Room 20"/></label><div className="admin-form-actions"><button className="btn btn-primary btn-xl" disabled={busy}>{busy?'Saving…':'Register doctor'}</button><button type="button" className="btn btn-outline btn-xl" onClick={()=>setShow(false)}>Cancel</button></div></form></Section>}
 <Section title="Doctors" eyebrow={`${doctors.length} REGISTERED`}><div className="doctor-admin-list">{doctors.map(d=><article className={`doctor-admin-row ${d.active?'':'inactive'}`} key={d.id} onClick={()=>setSelectedDoctor(d)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setSelectedDoctor(d)}}><div className="doctor-admin-avatar">{d.name?.slice(0,1)}</div><div className="doctor-admin-info"><strong>{d.name}</strong><span>{d.specialty} · {d.department}</span><small>Doctor ID #{d.id} · {d.registration_number||'Registration not listed'} · {d.room_number||'Room not assigned'}</small></div><div className="doctor-admin-status"><span className={`status-dot ${d.active?'active':''}`}/>{d.active?'Active':'Inactive'}</div><div className="doctor-admin-actions">{d.active&&<button className="btn btn-light" disabled={busy} onClick={e=>{e.stopPropagation();deactivate(d)}}>Remove</button>}</div></article>)}</div></Section>
 <Section title="Patients" eyebrow={`${patients.length} REGISTERED`}><div className="doctor-admin-list">{patients.map(p=><article className="doctor-admin-row" key={p.id} onClick={async()=>{try{setSelectedPatient((await api.adminPatient(auth.token,p.id)))}catch(e){setError(e)}}} role="button" tabIndex="0"><div className="doctor-admin-avatar">{p.name?.slice(0,1)}</div><div className="doctor-admin-info"><strong>{p.name}</strong><span>{p.age??'Age not provided'} · {p.gender||'Gender not provided'}</span><small>Patient ID #{p.id} · {p.email||'Email not provided'}{p.encounter_id?` · Encounter #${p.encounter_id}`:''}</small></div><div className="doctor-admin-status"><span className="status-dot active"/>View details</div></article>)}</div></Section>
 {selectedDoctor&&<div className="admin-detail-overlay" role="dialog" aria-modal="true"><div className="admin-detail-card card"><div className="section-head"><div><div className="eyebrow">DOCTOR PROFILE</div><h2>{selectedDoctor.name}</h2></div><button className="btn btn-light" onClick={()=>setSelectedDoctor(null)}>Close</button></div><div className="answer-evidence-grid"><div><span>Doctor ID</span><strong>#{selectedDoctor.id}</strong></div><div><span>Email</span><strong>{selectedDoctor.email||'Not provided'}</strong></div><div><span>Specialization</span><strong>{selectedDoctor.specialty||'Not provided'}</strong></div><div><span>Department</span><strong>{selectedDoctor.department||'Not provided'}</strong></div><div><span>Registration</span><strong>{selectedDoctor.registration_number||'Not provided'}</strong></div><div><span>Room</span><strong>{selectedDoctor.room_number||'Not provided'}</strong></div><div><span>Account status</span><strong>{selectedDoctor.active?'Active':'Inactive'}</strong></div></div></div></div>}
 {selectedPatient&&<div className="admin-detail-overlay" role="dialog" aria-modal="true"><div className="admin-detail-card card"><div className="section-head"><div><div className="eyebrow">PATIENT PROFILE</div><h2>{selectedPatient.name}</h2></div><button className="btn btn-light" onClick={()=>setSelectedPatient(null)}>Close</button></div><div className="answer-evidence-grid">{[['Patient ID',selectedPatient.id],['Name',selectedPatient.name],['Age',selectedPatient.age??'Not provided'],['Gender',selectedPatient.gender||'Not provided'],['Phone',selectedPatient.phone||'Not provided'],['Email',selectedPatient.email||'Not provided'],['Address',selectedPatient.address||'Not provided'],['Account status',selectedPatient.role==='patient'?'Active':'Not available']].map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v)}</strong></div>)}</div></div></div>}
</AdminLayout>}
